In [4]:
import numpy as np

print(np.arange(10))

print(np.arange(1,10))

np.arange(1,10,0.5)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [5]:
#ndarray
arr = np.arange(1,10)

arr.shape

(9,)

In [6]:
arr.itemsize * arr.size

72

In [10]:
#convert list to numpy array
list2d = [[1,2,3],[1,2,3]]
arr2d = np.asarray(list2d)
arr2d

array([[1, 2, 3],
       [1, 2, 3]])

In [12]:
#generate zeros
listzeros = np.zeros((4,4), dtype = 'int32')
listzeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [14]:
#linspace 
np.linspace(1,4)

array([1.        , 1.06122449, 1.12244898, 1.18367347, 1.24489796,
       1.30612245, 1.36734694, 1.42857143, 1.48979592, 1.55102041,
       1.6122449 , 1.67346939, 1.73469388, 1.79591837, 1.85714286,
       1.91836735, 1.97959184, 2.04081633, 2.10204082, 2.16326531,
       2.2244898 , 2.28571429, 2.34693878, 2.40816327, 2.46938776,
       2.53061224, 2.59183673, 2.65306122, 2.71428571, 2.7755102 ,
       2.83673469, 2.89795918, 2.95918367, 3.02040816, 3.08163265,
       3.14285714, 3.20408163, 3.26530612, 3.32653061, 3.3877551 ,
       3.44897959, 3.51020408, 3.57142857, 3.63265306, 3.69387755,
       3.75510204, 3.81632653, 3.87755102, 3.93877551, 4.        ])

In [19]:
#RANDO GENERATION
np.random.random((3,4))

array([[0.91794241, 0.47495319, 0.60914274, 0.31927642],
       [0.25772829, 0.04757683, 0.9041721 , 0.88631853],
       [0.46278824, 0.87997751, 0.52308487, 0.14169162]])

In [0]:
rar = np.random.random((3,4))



In [22]:
#slicing
rarr = np.random.random((4,5))
rarr[:,:]
rarr[1:3,:]
rarr[:,1:3]

array([[0.22947395, 0.28834094],
       [0.54232332, 0.73912196],
       [0.03912029, 0.48415111],
       [0.92284154, 0.06777707]])

In [0]:
import sys
import 